// 自 https://www.fscalc.com/assets/applicationSPA-9ffe0e9b….js 抽出的原始片段
// （生产环境压缩包，仅摘录与「地理位置」和「挨星」相关的函数，供复核）

// ── getMagNorthOffsetFromLatLng ──
getMagNorthOffsetFromLatLng();var e=this,i={center:this.get("latLng").lat()+","+this.get("latLng").lng(),zoom:this.get("zoom"),size:"640x640",scale:1,maptype:"satellite",sensor:"false"};console.log($.param(i)),this.set("mapImage",new Image),this.get("mapImage").onload=function(){e.storeMapImage()},this.get("mapImage").onerror=function(){e.imageLoadError()},this.get("mapImage").crossOrigin="anonymous",this.get("mapImage").src="/api/getMap?"+$.param(i)},imageLoadError:function(t){console.log("imageLoadError called e=",t),Fscalc.displaySystemMessage("Maps Rental Time Expired","nok"),window.history.back()},getMagNorthOffsetFromLatLngOLD:function(){var t={lat1:this.get("latLng").lat(),lon1:this.get("latLng").lng(),resultFormat:"xml"},e="http://www.ngdc.noaa.gov/geomag-web/calculators/calculateDeclination?"+$.param(t);console.log("remoteUrl=",e);var i="http://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20html%20where%20url%3D%22"+encodeURIComponent(e)+"%22&format=json";console.log("yahooService=",i);var n=this;$.ajax({url:i,type:"GET",dataType:"jsonp",success:function(t){if(console.log("results from noaa, data=",t),!t||!t.query.results)return alert("error while getting magnetic declination from noaa, please try again. If the problem persists, manually check http://www.ngdc.noaa.gov it may be down. This compass depends on noaa."),n.set("mapImage",null),void n.trigger("imageLoaded");console.log("from ngdc=",t.query.results.body.p),n.parseSuccess(t.query.results.body.p)},error:function(t){alert("error while getting magnetic declination from noaa or yahoo:",t.responseText+". Please try again. If the problem persists, manually check http://www.ngdc.noaa.gov it may be down.

// ── parseSuccess:function ──
parseSuccess:function(t){var e=parseFloat(t.declination).toFixed(1);this.addToNoaaCache(this.get("latLng").lat(),this.get("latLng").lng(),e),console.log("offset="+e),this.set("magneticNorthOffset",e),this.trigger("imageLoaded")},addToNoaaCache:function(t,e,i){for(;this.noaaCache.length>this.noaaCacheMaxSize;)this.noaaCache.shift(),console.log("noaaCache size limit reached, removed first element");var n={lat:t,lng:e,offsetRounded:i};this.noaaCache.push(n),console.log("addToNoaaCache called, new length=",this.noaaCache.length)},checkNoaaCache:function(t,e){for(var i=0;i<this.noaaCache.length;i++){var n=this.noaaCache[i];if(n.lat==t&&n.lng==e)return n.offsetRounded}return null},addToGoogleCache:function(t,e,i,n){for(;this.googleCache.length>this.googleCacheMaxSize;)this.googleCache.shift(),console.log("googleCache size limit reached, removed first element");var s={lat:t,lng:e,zoom:i,image:n};this.googleCache.push(s),console.log("addToGoogleCache called, new length=",this.googleCache.length)},checkGoogleCache:function(t,e,i){for(var n=0;n<this.googleCache.length;n++){var s=this.googleCache[n];if(s.lat==t&&s.lng==e&&s.zoom==i)return s.image}return null},parseSuccessOld:function(t){var e=t.replace(/\s+/g," ").replace(/^\s+|\s+$/g,"").split(" ")[4],i=parseFloat(e).toFixed(1);console.log("offset="+i),this.set("magneticNorthOffset",i),this.trigger("imageLoaded")},incCompassDegrees:function(){var t=this.get("compassDegrees");360<=(t+=.1)&&(t=0),this.set("compassDegrees",t)},decCompassDegrees:function(){var t=this.get("compassDegrees");(t-=.1)<0&&(t=359.9),this.set("compassDegrees",t)},incRulerPosition:function(){var t=this.get("rulerPosition");this.set("rulerPosition",++t)},decRule

// ── initMountains:function ──
initMountains:function(){0<this.mountains.length||(this.mountains[0]=new Fsutil.mountain(0,352.5,7.5,"N2","Rat"),this.mountains[1]=new Fsutil.mountain(15,7.5,22.5,"N3",""),this.mountains[2]=new Fsutil.mountain(30,22.5,37.5,"NE1","Ox"),this.mountains[3]=new Fsutil.mountain(45,37.5,52.5,"NE2",""),this.mountains[4]=new Fsutil.mountain(60,52.5,67.5,"NE3","Tiger"),this.mountains[5]=new Fsutil.mountain(75,67.5,82.5,"E1",""),this.mountains[6]=new Fsutil.mountain(90,82.5,97.5,"E2","Rabbit"),this.mountains[7]=new Fsutil.mountain(105,97.5,112.5,"E3",""),this.mountains[8]=new Fsutil.mountain(120,112.5,127.5,"SE1","Dragon"),this.mountains[9]=new Fsutil.mountain(135,127.5,142.5,"SE2",""),this.mountains[10]=new Fsutil.mountain(150,142.5,157.5,"SE3","Snake"),this.mountains[11]=new Fsutil.mountain(165,157.5,172.5,"S1",""),this.mountains[12]=new Fsutil.mountain(180,172.5,187.5,"S2","Horse"),this.mountains[13]=new Fsutil.mountain(195,187.5,202.5,"S3",""),this.mountains[14]=new Fsutil.mountain(210,202.5,217.5,"SW1","Sheep"),this.mountains[15]=new Fsutil.mountain(225,217.5,232.5,"SW2",""),this.mountains[16]=new Fsutil.mountain(240,232.5,247.5,"SW3","Monkey"),this.mountains[17]=new Fsutil.mountain(255,247.5,262.5,"W1",""),this.mountains[18]=new Fsutil.mountain(270,262.5,277.5,"W2","Rooster"),this.mountains[19]=new Fsutil.mountain(285,277.5,292.5,"W3",""),this.mountains[20]=new Fsutil.mountain(300,292.5,307.5,"NW1","Dog"),this.mountains[21]=new Fsutil.mountain(315,307.5,322.5,"NW2",""),this.mountains[22]=new Fsutil.mountain(330,322.5,337.5,"NW3","Boar"),this.mountains[23]=new Fsutil.mountain(345,337.5,352.5,"N1",""))},getMountain:function(t){if(352.5<=t||t<7.5)return this.mountains[0];for(var 

// ── initFlyingStars:function ──
initFlyingStars:function(){this.oddStarDirections[0]="yang",this.oddStarDirections[1]="yin",this.oddStarDirections[2]="yin",this.evenStarDirections[0]="yin",this.evenStarDirections[1]="yang",this.evenStarDirections[2]="yang",this.initFlyingStarPalaces(),this.initStaticFlyingStars()},initStaticFlyingStars:function(){var t=parseInt(this.model.get("year_built_temp")),e=Fsutil.periods[t];if(console.log("initStaticFlyingStars() called, period=",e),0<e.period)for(var i=0,n=this.palaces.C,s=e.period;i++<9;)n.baseStar=s,9<++s&&(s=1),n=this.palaces[n.next];var a=this.model.get("facing_degrees_temp"),o=Fsutil.getMountain(a),r=parseFloat(a)+180;359<r&&(r-=360);var l=Fsutil.getMountain(r);console.log("facingDirection=",o.name,"sittingDirection=",l.name);var c=o.name,d=c.slice(-1)-1,h=c.substring(0,c.length-1),u=this.palaces[h],p=u.baseStar,g=p;if(5==p)g=u.originalLoShu;var m=this.evenStarDirections[d];this.isOdd(g)&&(m=this.oddStarDirections[d]),console.log("center waterStar=",p,"direction=",m);var f=l.name,v=f.slice(-1)-1,y=f.substring(0,f.length-1),b=this.palaces[y],w=b.baseStar,x=w;if(5==w)x=b.originalLoShu;var S=this.evenStarDirections[v];if(this.isOdd(x)&&(S=this.oddStarDirections[v]),console.log("center mountainStar=",w,"direction=",S),0<e.period)for(i=0,n=this.palaces.C;i++<9;)n.waterStar=p,"yang"==m?9<++p&&(p=1):--p<=0&&(p=9),n=this.palaces[n.next];if(0<e.period)for(i=0,n=this.palaces.C;i++<9;)n.mountainStar=w,"yang"==S?9<++w&&(w=1):--w<=0&&(w=9),n=this.palaces[n.next];console.log("Palaces=",this.palaces)},isOdd:function(t){return t%2==1},initDynamicFlyingStars:function(){console.log("initDynamicFlyingStars() called");for(var t=this.calcControl.get("flyingStarYear"),e=this.ca

// ── initStaticFlyingStars:function ──
initStaticFlyingStars:function(){var t=parseInt(this.model.get("year_built_temp")),e=Fsutil.periods[t];if(console.log("initStaticFlyingStars() called, period=",e),0<e.period)for(var i=0,n=this.palaces.C,s=e.period;i++<9;)n.baseStar=s,9<++s&&(s=1),n=this.palaces[n.next];var a=this.model.get("facing_degrees_temp"),o=Fsutil.getMountain(a),r=parseFloat(a)+180;359<r&&(r-=360);var l=Fsutil.getMountain(r);console.log("facingDirection=",o.name,"sittingDirection=",l.name);var c=o.name,d=c.slice(-1)-1,h=c.substring(0,c.length-1),u=this.palaces[h],p=u.baseStar,g=p;if(5==p)g=u.originalLoShu;var m=this.evenStarDirections[d];this.isOdd(g)&&(m=this.oddStarDirections[d]),console.log("center waterStar=",p,"direction=",m);var f=l.name,v=f.slice(-1)-1,y=f.substring(0,f.length-1),b=this.palaces[y],w=b.baseStar,x=w;if(5==w)x=b.originalLoShu;var S=this.evenStarDirections[v];if(this.isOdd(x)&&(S=this.oddStarDirections[v]),console.log("center mountainStar=",w,"direction=",S),0<e.period)for(i=0,n=this.palaces.C;i++<9;)n.waterStar=p,"yang"==m?9<++p&&(p=1):--p<=0&&(p=9),n=this.palaces[n.next];if(0<e.period)for(i=0,n=this.palaces.C;i++<9;)n.mountainStar=w,"yang"==S?9<++w&&(w=1):--w<=0&&(w=9),n=this.palaces[n.next];console.log("Palaces=",this.palaces)},isOdd:function(t){return t%2==1},initDynamicFlyingStars:function(){console.log("initDynamicFlyingStars() called");for(var t=this.calcControl.get("flyingStarYear"),e=this.calcControl.get("flyingStarMonthIndex"),i=Fsutil.years[t],n=i.yearlyStar,s=0,a=this.palaces.C;s++<9;)a.yearlyStar=n,9<++n&&(n=1),a=this.palaces[a.next];var o=i.monthsArray[e];for(s=0,a=this.palaces.C;s++<9;)a.monthlyStar=o,9<++o&&(o=1),a=this.palaces[a.next]},fiveYellowWedges:{},initFi
